INSERT INTO users 
VALUES
(1, 'asdf', 'asdf'),
(2, 'pokemaster', '123'),
(3, 'ryan', 'mypass'),
(4, 'jason', 'lol21'),
(5, 'sihno master', 'biddof'),
(6, 'yooyyoy', 'a password'),
(7, 'hi', 'sf071'),
(8, 'brock', '1rj1013'),
(9, 'ash', 'jslkf213'),
(10, 'yoyoyo', 'f10f11280');

INSERT INTO decks VALUES
(1, 1111, 'my-deck'),
(1, 1110, 'my-deck2'),
(2, 1180, 'pokemaster-deck1'),
(2, 1412, 'pokemaster-deck2'),
(2, 1241, 'pokemaster-battledeck1'),
(2, 1251, 'pokemaster-battledeck2'),
(2, 4121, 'special-collection'),
(3, 1511, 'jason1'),
(3, 5155, '1deck'),
(3, 9011, 'battledeck'),
(3, 7199, 'battledeck2'),
(3, 1471, 'anotherDeck'),
(4, 4589, 'jasonsDeck'),
(4, 4177, 'jasonsDeck2'),
(4, 4851, 'jasonsCoolDeck'),
(4, 4188, 'jasonsFinalDeck'),
(5, 5718, 'sihnoMasters'),
(6, 6001, 'myDeck'),
(6, 6002, 'a-deck'),
(6, 6971, 'anotherDeck'),
(6, 6781, 'deckStuff'),
(6, 7914, 'deckfinal'),
(7, 1512, 'deck-hi'),
(8, 1051, 'deckBrock'),
(9, 8583, 'deck-Ash'),
(10, 1184, 'hosDeck');

INSERT INTO sets VALUES
('a1', 'Sword & Shield Brilliant Stars', 'Sword & Shield Brilliant Stars', 172, 999, 'Legal', 'Banned', NULL, 'Blah', 'Blah', 'Blah', 
'https://images.pokemontcg.io/swsh9/symbol.png', 'https://images.pokemontcg.io/swsh9/logo.png'),
('a2', 'Diamond & Peral Sinnohs Revenge', 'Diamond & Peral Sihnos Revenge', 173, 999, 'Legal', 'Banned', NULL, 'Blah', 'Blah', 'Blah', 
'https://images.pokemontcg.io/swsh9/symbol.png', 'https://images.pokemontcg.io/swsh9/logo.png'),
('a3', 'Red and Green Final Form', 'Red and Green Final Form', 174, 999, 'Legal', 'Banned', NULL, 'Blah', 'Blah', 'Blah', 
'https://images.pokemontcg.io/swsh9/symbol.png', 'https://images.pokemontcg.io/swsh9/logo.png'),
('a4', 'Red and Green A New Beginning', 'Red and Green A New Beginning', 175, 999, 'Legal', 'Banned', NULL, 'Blah', 'Blah', 'Blah', 
'https://images.pokemontcg.io/swsh9/symbol.png', 'https://images.pokemontcg.io/swsh9/logo.png'),
('a5', 'Alola Beginnings', 'Alola Beginnings', 176, 999, 'Legal', 'Banned', NULL, 'Blah', 'Blah', 'Blah', 
'https://images.pokemontcg.io/swsh9/symbol.png', 'https://images.pokemontcg.io/swsh9/logo.png'),
('a6', 'Kanto The Revenge of Team Rocket', 'Kanto The Revenge of Team Rocket', 177, 999, 'Legal', 'Banned', NULL, 'Blah', 'Blah', 'Blah', 
'https://images.pokemontcg.io/swsh9/symbol.png', 'https://images.pokemontcg.io/swsh9/logo.png'),
('a7', 'Hoenn, Waves of Fate', 'Hoenn, Waves of Fate', 178, 999, 'Legal', 'Banned', NULL, 'Blah', 'Blah', 'Blah', 
'https://images.pokemontcg.io/swsh9/symbol.png', 'https://images.pokemontcg.io/swsh9/logo.png');

INSERT INTO cards VALUES 
('10', 'Charmandar', 'Pokemon', '{"Basic"}', '{"Fire"}', '{"Rules go here"}', 
'a1', 1, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('11', 'Biddof', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}', 
'a1', 2, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('12', 'Stunky', 'Pokemon', '{"Basic"}', '{"Dark","Poison"}', '{"Rules go here"}', 
'a1', 3, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('13', 'Meditite', 'Pokemon', '{"Basic"}', '{"Fight","Phycic"}', '{"Rules go here"}', 
'a1', 4, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('14', 'Whiscash', 'Pokemon', '{"Basic"}', '{"Water","Ground"}', '{"Rules go here"}', 
'a1', 5, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('15', 'Gastly', 'Pokemon', '{"Basic"}', '{"Poison","Ghost"}', '{"Rules go here"}', 
'a1', 6, 'Hasuno', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('16', 'Lopunny', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}', 
'a1', 7, 'Hasuno', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('17', 'Starly', 'Pokemon', '{"Basic"}', '{"Flying","Normal"}', '{"Rules go here"}', 
'a1', 8, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('18', 'Bulbasaur', 'Pokemon', '{"Basic"}', '{"Grass","Poison"}', '{"Rules go here"}',
'a1', 9, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('19', 'Blastoise', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}',
'a1', 10, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png');

INSERT INTO cards VALUES 
('20', 'Weedle', 'Pokemon', '{"Basic"}', '{"Bug","Poison"}', '{"Rules go here"}', 
'a2', 11, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('21', 'Pidgey', 'Pokemon', '{"Basic"}', '{"Normal","Flying"}', '{"Rules go here"}', 
'a2', 12, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('22', 'Rattata', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}', 
'a2', 13, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('23', 'Meditite', 'Pokemon', '{"Basic"}', '{"Fight","Phycic"}', '{"Rules go here"}', 
'a2', 14, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('24', 'Arbok', 'Pokemon', '{"Basic"}', '{"Poison"}', '{"Rules go here"}', 
'a2', 15, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('25', 'Pikachu', 'Pokemon', '{"Basic"}', '{"Electric"}', '{"Rules go here"}', 
'a2', 16, 'Getty', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('26', 'Sandshrew', 'Pokemon', '{"Basic"}', '{"Ground"}', '{"Rules go here"}', 
'a2', 17, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('27', 'Nidoran', 'Pokemon', '{"Basic"}', '{"Poison"}', '{"Rules go here"}', 
'a2', 18, 'Getty', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('28', 'Nidorina', 'Pokemon', '{"Basic"}', '{"Poison"}', '{"Rules go here"}',
'a2', 19, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('29', 'Clefairy', 'Pokemon', '{"Basic"}', '{"Fairy"}', '{"Rules go here"}',
'a2', 20, 'Getty', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png');

INSERT INTO cards VALUES 
('30', 'Vulpix', 'Pokemon', '{"Basic"}', '{"Fire"}', '{"Rules go here"}', 
'a3', 21, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/6/60/037Vulpix.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('31', 'Ninetales', 'Pokemon', '{"Basic"}', '{"Fire"}', '{"Rules go here"}', 
'a3', 22, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/0/05/038Ninetales.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('32', 'JigglyPuff', 'Pokemon', '{"Basic"}', '{"Normal","Fairy"}', '{"Rules go here"}', 
'a3', 23, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('33', 'Zubat', 'Pokemon', '{"Basic"}', '{"Poison","Flying"}', '{"Rules go here"}', 
'a3', 24, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('34', 'Oddish', 'Pokemon', '{"Basic"}', '{"Poison","Grass"}', '{"Rules go here"}', 
'a3', 25, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('35', 'Paras', 'Pokemon', '{"Basic"}', '{"Bug","Grass"}', '{"Rules go here"}', 
'a3', 26, 'Getty', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('36', 'Venomoth', 'Pokemon', '{"Basic"}', '{"Bug","Poison"}', '{"Rules go here"}', 
'a3', 27, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('37', 'Diglett', 'Pokemon', '{"Basic"}', '{"Ground"}', '{"Rules go here"}', 
'a3', 28, 'Getty', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('38', 'Dugtrio', 'Pokemon', '{"Basic"}', '{"Ground"}', '{"Rules go here"}',
'a3', 29, 'Hasuno', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('39', 'Meowth', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}',
'a3', 30, 'Getty', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png');

INSERT INTO cards VALUES 
('40', 'Phyduck', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a4', 31, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/6/60/037Vulpix.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('41', 'Mankey', 'Pokemon', '{"Basic"}', '{"Fighting"}', '{"Rules go here"}', 
'a4', 32, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/0/05/038Ninetales.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('42', 'Growlithe', 'Pokemon', '{"Basic"}', '{"Fire"}', '{"Rules go here"}', 
'a4', 33, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('43', 'Poliwag', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a4', 34, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('44', 'Abra', 'Pokemon', '{"Basic"}', '{"Psychic"}', '{"Rules go here"}', 
'a4', 35, 'Thomas', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('45', 'Machop', 'Pokemon', '{"Basic"}', '{"Fighting"}', '{"Rules go here"}', 
'a4', 36, 'Thomas', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('46', 'Bellsprout', 'Pokemon', '{"Basic"}', '{"Grass","Poison"}', '{"Rules go here"}', 
'a4', 37, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('47', 'Tentacool', 'Pokemon', '{"Basic"}', '{"Water","Poison"}', '{"Rules go here"}', 
'a4', 38, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('48', 'Geodude', 'Pokemon', '{"Basic"}', '{"Ground","Rock"}', '{"Rules go here"}',
'a4', 39, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('49', 'Golem', 'Pokemon', '{"Basic"}', '{"Ground","Rock"}', '{"Rules go here"}',
'a4', 40, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png');

INSERT INTO cards VALUES 
('50', 'Ponyta', 'Pokemon', '{"Basic"}', '{"Fire"}', '{"Rules go here"}', 
'a5', 41, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/6/60/037Vulpix.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('51', 'Rapidash', 'Pokemon', '{"Basic"}', '{"Fire"}', '{"Rules go here"}', 
'a5', 42, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/0/05/038Ninetales.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('52', 'Slowpoke', 'Pokemon', '{"Basic"}', '{"Psychic"}', '{"Rules go here"}', 
'a5', 43, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('53', 'Magnemite', 'Pokemon', '{"Basic"}', '{"Electric","Steel"}', '{"Rules go here"}', 
'a5', 44, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('54', 'Doduo', 'Pokemon', '{"Basic"}', '{"Normal","Flying"}', '{"Rules go here"}', 
'a5', 45, 'Thomas', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('55', 'Seel', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a5', 46, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('56', 'Grimer', 'Pokemon', '{"Basic"}', '{"Dark","Poison"}', '{"Rules go here"}', 
'a5', 47, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('57', 'Shellder', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a5', 48, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('58', 'Onix', 'Pokemon', '{"Basic"}', '{"Ground","Rock"}', '{"Rules go here"}',
'a5', 49, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('59', 'Drowzee', 'Pokemon', '{"Basic"}', '{"Psychic"}', '{"Rules go here"}',
'a5', 50, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png');

INSERT INTO cards VALUES 
('60', 'Krabby', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a6', 51, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/6/60/037Vulpix.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('61', 'Voltorb', 'Pokemon', '{"Basic"}', '{"Electric"}', '{"Rules go here"}', 
'a6', 52, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/0/05/038Ninetales.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('62', 'Exeguttor', 'Pokemon', '{"Basic"}', '{"Grass","Psychic"}', '{"Rules go here"}', 
'a6', 53, 'Thomas', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('63', 'Cubone', 'Pokemon', '{"Basic"}', '{"Ground"}', '{"Rules go here"}', 
'a6', 54, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('64', 'Morowak', 'Pokemon', '{"Basic"}', '{"Ground"}', '{"Rules go here"}', 
'a6', 55, 'Thomas', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('65', 'Hitmonlee', 'Pokemon', '{"Basic"}', '{"Fighting"}', '{"Rules go here"}', 
'a6', 56, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('66', 'Lickitung', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}', 
'a6', 57, 'Thomas', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('67', 'Koffing', 'Pokemon', '{"Basic"}', '{"Poison"}', '{"Rules go here"}', 
'a6', 58, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('68', 'Rhyhorn', 'Pokemon', '{"Basic"}', '{"Ground","Rock"}', '{"Rules go here"}',
'a6', 59, 'Thomas', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('69', 'Chansey', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}',
'a6', 60, 'Thomas', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png');

INSERT INTO cards VALUES 
('70', 'Horsea', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a7', 61, 'Gerry', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/6/60/037Vulpix.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('71', 'Staryu', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a7', 62, 'Gerry', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://archives.bulbagarden.net/media/upload/0/05/038Ninetales.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('72', 'Mr. Mime', 'Pokemon', '{"Basic"}', '{"Fairy","Psychic"}', '{"Rules go here"}', 
'a7', 63, 'Gerry', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('73', 'Jynx', 'Pokemon', '{"Basic"}', '{"Ice","Psychic"}', '{"Rules go here"}', 
'a7', 64, 'Gerry', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('74', 'Magmar', 'Pokemon', '{"Basic"}', '{"Fire"}', '{"Rules go here"}', 
'a7', 65, 'Hasuno', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('75', 'Pinsir', 'Pokemon', '{"Basic"}', '{"Bug"}', '{"Rules go here"}', 
'a7', 66, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('76', 'Tauros', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}', 
'a7', 67, 'Hasuno', 'Common', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('77', 'Gyarados', 'Pokemon', '{"Basic"}', '{"Water"}', '{"Rules go here"}', 
'a7', 68, 'Hasuno', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('78', 'Ditto', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}',
'a7', 69, 'Hasuno', 'Super Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png'),
('79', 'Eevee', 'Pokemon', '{"Basic"}', '{"Normal"}', '{"Rules go here"}',
'a7', 70, 'Hasuno', 'Rare', 'Flavor Text', 'Legal', 'Banned', NULL,
'F', 'https://images.pokemontcg.io/swsh9/87.png', 'https://images.pokemontcg.io/swsh9/87_hires.png');

INSERT INTO pokemon VALUES
('10', 10, 100, 461, 'Charmander', NULL),
('11', 12, 80, 444, 'Biddof', NULL),
('12', 15, 110, 554, 'biddof', NULL),
('13', 16, 110, 151, 'Medidite', NULL),
('14', 10, 100, 461, 'Whiscash', NULL),
('15', 12, 80, 444, 'Gastly', NULL),
('16', 15, 110, 554, 'Lopunny', NULL),
('17', 16, 110, 151, 'Starly', NULL),
('18', 17, 190, 154, 'Bulbasaur', NULL),
('19', 15, 89, 193, 'Blastoise', NULL),
('20', 10, 100, 461, 'Weedle', NULL),
('21', 12, 80, 444, 'Pidgey', NULL),
('22', 15, 110, 554, 'Rattata', NULL),
('23', 16, 110, 151, 'Meditite', NULL),
('24', 10, 100, 461, 'Arbok', NULL),
('25', 12, 80, 444, 'Pikachu', NULL),
('26', 15, 110, 554, 'Sandshrew', NULL),
('27', 16, 110, 151, 'Nidoran', NULL),
('28', 17, 190, 154, 'Nidorina', NULL),
('29', 15, 89, 193, 'Clefairy', NULL),
('30', 10, 100, 461, 'Vulpix', NULL),
('31', 12, 80, 444, 'Ninetales', NULL),
('32', 15, 110, 554, 'JigglyPuff', NULL),
('33', 16, 110, 151, 'Zubat', NULL),
('34', 10, 100, 461, 'Oddish', NULL),
('35', 12, 80, 444, 'Paras', NULL),
('36', 15, 110, 554, 'Venomoth', NULL),
('37', 16, 110, 151, 'Diglett', NULL),
('38', 17, 190, 154, 'Dugtrio', NULL),
('39', 15, 89, 193, 'Meowth', NULL),
('40', 10, 100, 461, 'Phyduck', NULL),
('41', 12, 80, 444, 'Mankey', NULL),
('42', 15, 110, 554, 'Growlithe', NULL),
('43', 16, 110, 151, 'Poliwag', NULL),
('44', 10, 100, 461, 'Abra', NULL),
('45', 12, 80, 444, 'Machop', NULL),
('46', 15, 110, 554, 'Bellsprout', NULL),
('47', 16, 110, 151, 'Tentacool', NULL),
('48', 17, 190, 154, 'Geodude', NULL),
('49', 15, 89, 193, 'Golem', NULL),
('50', 10, 100, 461, 'Ponyta', NULL),
('51', 12, 80, 444, 'Rapidash', NULL),
('52', 15, 110, 554, 'Slowpoke', NULL),
('53', 16, 110, 151, 'Magnemite', NULL),
('54', 10, 100, 461, 'Doduo', NULL),
('55', 12, 80, 444, 'Seel', NULL),
('56', 15, 110, 554, 'Grimer', NULL),
('57', 16, 110, 151, 'Shellder', NULL),
('58', 17, 190, 154, 'Onix', NULL),
('59', 15, 89, 193, 'Drowzee', NULL),
('60', 10, 100, 461, 'Krabby', NULL),
('61', 12, 80, 444, 'Voltorb', NULL),
('62', 15, 110, 554, 'Exeguttor', NULL),
('63', 16, 110, 151, 'Cubone', NULL),
('64', 10, 100, 461, 'Morowak', NULL),
('65', 12, 80, 444, 'Hitmonlee', NULL),
('66', 15, 110, 554, 'Lickitung', NULL),
('67', 16, 110, 151, 'Koffing', NULL),
('68', 17, 190, 154, 'Rhyhorn', NULL),
('69', 15, 89, 193, 'Chansey', NULL);
('70', 10, 100, 461, 'Horsea', NULL),
('71', 12, 80, 444, 'Staryu', NULL),
('72', 15, 110, 554, 'Mr. Mime', NULL),
('73', 16, 110, 151, 'Jynx', NULL),
('74', 10, 100, 461, 'Magmar', NULL),
('75', 12, 80, 444, 'Pinsir', NULL),
('76', 15, 110, 554, 'Tauros', NULL),
('77', 16, 110, 151, 'Gyarados', NULL),
('78', 17, 190, 154, 'Ditto', NULL),
('79', 15, 89, 193, 'Eevee', NULL);




